# Generated by Django 5.0.2 on 2024-02-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
